services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8000:8080"
    env_file:
      - .env  # Load database credentials from .env file
    depends_on:
      - db

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    env_file:
      - .env  # Load database credentials from .env file
    volumes:
      - postgres_data:/var/lib/postgresql/data


  test-app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8001:8080"
    env_file:
      - .env.test  # Load database credentials from .env.test file
    depends_on:
      - test-db

  test-db:
    image: postgres:15
    ports:
      - "5433:5432"
    env_file:
      - .env.test  # Load database credentials from .env.test file


volumes:
  postgres_data:
