services:
  # PRODUCTION ENVIRONMENT
  app-frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    depends_on:
      - app

  app:
    build:
      context: backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    ports:
      - "8000:8080"
    env_file:
      - backend/.env  # Load database credentials from .env file
    depends_on:
      - db

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    env_file:
      - backend/.env  # Load database credentials from .env file
    volumes:
      - postgres_data:/var/lib/postgresql/data


# TEST ENVIRONMENT
  test-app-frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "4201:4200"
    depends_on:
      - test-app

  test-app:
    build:
      context: backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    ports:
      - "8001:8080"
    env_file:
      - backend/.env.test  # Load database credentials from .env.test file
    depends_on:
      - test-db

  test-db:
    image: postgres:15
    ports:
      - "5433:5432"
    env_file:
      - backend/.env.test  # Load database credentials from .env.test file


volumes:
  postgres_data:
